### ISSUE TITLE
Check username before password prompt

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_cli#107]
When specifying the wrong username and no password, the CLI still asks for the password. Suggestion to check if the username is correct before prompting.

**Comment by inaod568** [comment]
Removing this. This should not be done. The user should know the correct username and should not get information on if the username is incorrect or not before entering password. Insecure.

**Comment by ewels** [comment]
I think the simplest is to say "username or password is incorrect"

Then it's clear that it could be either without giving anything away.

**Comment by inaod568** [comment]
Yep, I've fixed it 👍🏻
