### ISSUE TITLE
`rm` throws error about non-existing `warn_if_many` if file does not exist

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_cli#128]
Tried to remove a file which did not exist and got:
```
data_lister.DataLister.warn_if_many(count=len(not_exists) + len(delete_failed))
AttributeError: type object 'DataLister' has no attribute 'warn_if_many'
```

The `rm` previously listed the files which where not successfully removed within the system, but warned if it was too many. The pagination should be added here in the same way as for in the `data_lister.py`

**Comment by ewels** [comment]
Ah sorry, I guess I didn't check if that function was used elsewhere.. 🙄 My bad!

**Comment by inaod568** [comment]
No worries 👍🏻 Would've removed that function and switched to pagination or something else at some point anyway
