### ISSUE TITLE
Make a decision on 2FA or MFA to offer to users

### ISSUE THREAD

**Issue by worukan** [ScilifelabDataCentre/dds_cli#138]
Two or multi factor authentication helps strengthen the security of the system by means of additional factors to identify users. They also help with the problem of strong passwords and maintaining/remembering them. We would like to improve both the security and the user experience in the system.

**Comment by worukan** [comment]
2FA is two, MFA is more than one. Do we want to set the number of factors to two or another number? How many options do we want and/or accommodate? What do we gain by increasing the number of factors and how important is that to us?

**Comment by inaod568** [comment]
https://github.com/pyauth/pyotp

**Comment by worukan** [comment]
Commenting here to gather the information that has been discussed over chats.
Hardware based factor does not seem suitable/applicable. SMS is considered against privacy.

Available multi-factor options:
1.TOTP: Time-Based One-Time Password Algorithm
2.One-Time number sent via e-mail

Reference:
https://cheatsheetseries.owasp.org/cheatsheets/Multifactor_Authentication_Cheat_Sheet.html

**Comment by inaod568** [comment]
MFA -- required for KRT 332.
