### ISSUE TITLE
DDS_METHODS not used?

### ISSUE THREAD

**Issue by alneberg** [ScilifelabDataCentre/dds_cli#148]
https://github.com/ScilifelabDataCentre/dds_cli/blob/7b09e75886ee96391b15f08163443280f4b4ee9a/dds_cli/__init__.py#L20

Just doing a bit of code review to get into the code. I saw this was added recently in https://github.com/ScilifelabDataCentre/dds_cli/commit/1d99e6fda0ead9c706b90e4e938da51e68ca9946, but it doesn't seem to be used anywhere? I'm not sure it's needed either, I guess click should already keep track of which commands are allowed? But maybe I'm wrong?

**Comment by inaod568** [comment]
Yes this will probably be removed when we change the auth process but I had some initial thought with this so lets keep it for now

**Comment by ewels** [comment]
Can always add it back later? If we remove it in a single PR / commit we can even just revert that in a single command. I'm always in favour of deleting as much code as possible.. 💥 😁

**Comment by inaod568** [comment]
Yes, but I added it relatively recently so I don't want to delete this before I've had a chance to look at it and see what I was thinking there 👍🏻
