### ISSUE TITLE
Possibility to save and reuse a token

### ISSUE THREAD

**Issue by alneberg** [ScilifelabDataCentre/dds_cli#187]
I would suggest a new endpoint for example:

```
dds login
```
or perhaps
```
dds session
```
That would fetch a fresh token and either return it on the command line or save it to a file. 

If such token exists/is given it should be used for all requests until it fails or is renewed.

This relates to the possibility of using the cli in an automated fashion.

**Comment by inaod568** [comment]
From discussion with @alneberg: `--username` does not override the use of the token. If it's another user, it's the users responsibility to have a logout routine and to use the correct account when using DDS. A possible future enhancement can be to add a `--force-auth` flag to not use the saved token, however this is IF the users mention that this is a useful feature.
