### ISSUE TITLE
Reconsider use of os.umask(0)

### ISSUE THREAD

**Issue by alneberg** [ScilifelabDataCentre/dds_cli#192]
We currently save all files downloaded with very generous permissions. I think this should be changed.

I believe the change is quite easy, where
https://github.com/ScilifelabDataCentre/dds_cli/blob/958499d86bc26b1fea53177e62c55fa7cbabdaba/dds_cli/file_handler_remote.py#L60

should be using some other argument than just `0`.

**Comment by inaod568** [comment]
@alneberg I think is was fixed in your last PR?

**Comment by inaod568** [comment]
All instances of `os.umask` has now been removed.
