### ISSUE TITLE
UX improvement for `dds project status delete`

### ISSUE THREAD

**Issue by MatthiasZepper** [ScilifelabDataCentre/dds_cli#224]
When running `dds project status delete` on a still fairly small project (2650 items, 160MB), it took quite a while until the success message is shown.

I could be nice to display some kind of progress bar or spinner to the user so that there is a visual feedback of the operation being performed. Otherwise it seems that the CLI is hung until the _Project someunit001 updated to status Deleted All files in someunit001 deleted and project info cleared_ is shown, which took about a minute or two? (rough estimate)

**Comment by inaod568** [comment]
I believe this is fixed with Linus' latest delete-fixes
