### ISSUE TITLE
Change `--is_sensitive` flag when creating projects

### ISSUE THREAD

**Issue by alneberg** [ScilifelabDataCentre/dds_cli#243]
With the improved flow for sensitive projects, we will treat all projects as sensitive so I propose that we change the flag `--is_sensitive` to `--non_sensitive` and correspondingly reverse the meaning. `--non_sensitive` should be False by default.

**Comment by inaod568** [comment]
Good point. At the moment all projects are handled in the same way though so I'll connect it to the changes I started.

**Comment by inaod568** [comment]
Closed with #913 and #246
