### ISSUE TITLE
Add signing to commits `-S`

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_cli#247]
Suggested by Zishan: Setup PGP keys and begin using  `git commit -S` to sign the commits. 
Good practice. See comment below for link describing how to set it up.

- [x] @inaod568 
- [x] @talavis 
- [x] @alneberg 
- [x] @zishanmirza 
- [x] @aanil 
- [x] @MatthiasZepper 
- [ ] @ewels

**Comment by inaod568** [comment]
As @talavis shared 
https://gist.github.com/phortuin/cf24b1cca3258720c71ad42977e1ba57

**Comment by zishanmirza** [comment]
The `--signoff` flag adds text to end of the commit.

Example:
Signed-off-by: Name \<email\>

**Comment by inaod568** [comment]
@ewels Do you have this signing thing set up (maybe prior to this as well)? If not, could you look into it when you have the chance?
