### ISSUE TITLE
Update docs - `dds auth info` note - no info displayed atm

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_cli#285]

**Comment by aanil** [comment]
Wouldn't the expiration time be always displayed only if this PR is merged? https://github.com/ScilifelabDataCentre/dds_cli/pull/260

Otherwise only `Token is OK!` will be displayed unless its nearing the expiration time.

**Comment by inaod568** [comment]
Yes exactly. This card is to just update the docs saying that the information I wrote there (which applied to the token before it was changed) is currently incorrect. Otherwise we'll get questions about the docs saying one thing but the output being `Token is OK!`
