### ISSUE TITLE
Customize validation message when looking through project contents

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_cli#286]
![Skärmavbild 2022-02-28 kl  11 51 36](https://user-images.githubusercontent.com/35953392/155971727-c1c69144-bffb-43bf-88f7-46e22ead9482.png)

Should clarify the "Invalid input" message

**Comment by ewels** [comment]
Prompt code is here: https://github.com/ScilifelabDataCentre/dds_cli/blob/3396e7275dc008e15a2acea906f31e6b205b2ab9/dds_cli/__main__.py#L179-L184

I can't immediately see an option to customise the error message (though I feel like I have done this before 🤔 ), so the easy option is to just print an additional log message making it super clear what is expected.

I'm actually not sure if the `validate`  function is required here as we are already providing a list of choices. So it could be that simply removing this line gives a nicer error message.

**Comment by inaod568** [comment]
Moving to Jira.
