### ISSUE TITLE
Issue mixing existing and new files in put command (dds_failed_delivery.txt file not getting created)

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_cli#300]
**From tester:**

I got this error after trying to upload the same directory twice, but the dds_failed_delivery.txt file does not exist.
Errors occurred during upload.
If you wish to retry the upload, re-run the `dds data put` command again, specifying the same options as you did now. To also overwrite the files that were uploaded, also add the `--overwrite` flag at the end of the
command.

See `/dds_testing/DataDelivery_2022-03-01_14-10-51/logs/dds_failed_delivery.txt` for more information.
On the second upload attempt I had added another file to the directory and that was successfully uploaded, but it’s not clear from the message that that was the case.

**Comment by talavis** [comment]
The lack of the file seems to not be a bug. Instead the issue seems to be related to mixing already uploaded files with new files in a `dds data put` command.

```
$ dds data put -p <project>  -s file1 -s file2
/.../
ERROR    No data to upload.

$ dds data put -p <project>  -s file1 -s file2 -s file3
/.../
Upload ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  •  100.0%
Errors occurred during upload.
If you wish to retry the upload, re-run the `dds data put` command again, specifying the same options as you did now. To also overwrite the files that were uploaded, also add the `--overwrite` flag at the end of the command.

See /<path>/logs/dds_failed_delivery.txt for more information.

$ dds data put -p <project>  -s file1 -s file2 -s file3
/.../
ERROR    No data to upload.
```
