### ISSUE TITLE
non-interactive login

### ISSUE THREAD

**Issue by alneberg** [ScilifelabDataCentre/dds_cli#301]
Once we have TOTP as an option for mfa authentication, we can have non-interactive login this way:

```bash
echo $my_secret_password_variable | dds auth login --username <username> --TOTP <totp> --password-stdin
```

It's otherwise difficult to specify both the MFA code and the password on stdin, and we don't want to have password as a cleartext option.

**Comment by inaod568** [comment]
Moving to Jira.
