### ISSUE TITLE
Specify which field causes an error

### ISSUE THREAD

**Issue by talavis** [ScilifelabDataCentre/dds_cli#317]
Currently the cli (`dds project create`) gives the error
```
ERROR    Length must be between 1 and 255.
```
without specifying which field must be that length. If possible, try to add information about which field caused the error.

Also true for e.g. 
```
ERROR    Not a valid email address.
```

----

The error information including which field it involves should already be returned from the API, but it's not parsed by the CLI at the moment. Look at the example in `add_user` function in the `dds_cli/account_manager.py` module.

**Comment by inaod568** [comment]
This should be returned from the api now, just requires some response parsing in the cli.
