### ISSUE TITLE
AttributeError: 'DDSCLIException' object has no attribute 'ctx' when incorrect path to data 

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_cli#323]
`dds data put` with "incorrect path" to data gives a huge error message ending with
```
AttributeError: 'DDSCLIException' object has no attribute 'ctx'
```

**Comment by talavis** [comment]
Isn't this the one that was supposed to be fixed by the rich-click upgrade?

**Comment by inaod568** [comment]
Yes. We can close this now.
