### ISSUE TITLE
Bug: Windows file permissions prevent token from being written

### ISSUE THREAD

**Issue by MatthiasZepper** [ScilifelabDataCentre/dds_cli#381]
One bug that I noticed during testing in Windows: Python's touch command failed to set the file permissions correctly on Windows 10, hence the token was not written to the file:   

https://github.com/ScilifelabDataCentre/dds_cli/blob/ca1e25fc2b08a857249d82239f29659495181817/dds_cli/user.py#L254-L260

To circumvent, I had to manually create an empty file first and set the correct permissions to obtain a token.

This is effectively a blocker to use the DDS because a regular user is likely not able to obtain a token. 

Therefore I think that there should be means to override `check_token_file_permissions` in a worst case scenario? Alternatively, the token should then be somehow cached for a while e.g. in the RAM, such that it is at least preserved as long as that terminal is open?   

https://github.com/ScilifelabDataCentre/dds_cli/blob/ca1e25fc2b08a857249d82239f29659495181817/dds_cli/user.py#L276-L282

**Comment by talavis** [comment]
Confirmed in an actual Windows 10 installation.

**Comment by talavis** [comment]
The CLI graphics also look terrible:
![IMG_20220314_101108.jpg](https://images.zenhubusercontent.com/5be968ab7610415c19d16ac7/cc49291c-f2a1-47c1-949b-bef4a08a9e23)
