### ISSUE TITLE
Bundle CLI with pyinstaller

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_cli#414]
https://pyinstaller.readthedocs.io/en/stable/

**Comment by MatthiasZepper** [comment]
After installing the development dependencies, it is just this command executed in the main directory of the repo.

`pyinstaller -F -c -n  dds -i resources/scilifelab.icns  --exclude-module=tests  --target-arch x86_64 --log-level INFO dds_cli/__init__.py`

This should create a temporary `build` directory and the finished executable should then be in `dist`.
