### ISSUE TITLE
Send email to other unit admins when a unit admin resets their password

### ISSUE THREAD

**Issue by inaod568** [ScilifelabDataCentre/dds_cli#431]
In here:

https://github.com/ScilifelabDataCentre/dds_web/blob/1aa95eb8772831c87298fd8b7c8d909af6dc7f80/dds_web/web/user.py#L434-L461

1. If the user is a Unit Admin, get other unit admins from that users unit
2. Generate email and send information about that they need to reset the users project access with dds project access fix
Template for email sending (no link used this time)

https://github.com/ScilifelabDataCentre/dds_web/blob/1aa95eb8772831c87298fd8b7c8d909af6dc7f80/dds_web/utils.py#L255-L277

**Comment by zishanmirza** [comment]
Fixed in https://github.com/ScilifelabDataCentre/dds_web/pull/1110.
