### ISSUE TITLE
Bug: DDS can't start two deliveries at the same time

### ISSUE THREAD

**Issue by Aratz** [ScilifelabDataCentre/dds_cli#528]
It seems like `dds` can't handle two uploads started simultaneously (i.e. started within the same second). This is because in that case, the staging directories from these deliveries will have the same name.

## Steps to reproduce
1. create two projects in DDS
2. create two dummy data files
3. Run the following command: 
```
dds --log-file dds.log data put -p <project1> -s <file1> & dds --log-file dds.log data put -p <project2> -s <file2>
```

## Expected result
DDS uploads both files to their respective projects and there are traces of this in the logs

## Actual result
- One of the deliveries fails because the staging directory (i.e. `DataDelivery_YYYY-MM-DD_hh-mm-ss`) already exists.
- There is no trace of the failed delivery in the logs

**Comment by inaod568** [comment]
Thanks for the bug report! 

@valyo This is also a Zendesk ticket and we'll continue the discussion from there 👍🏻
