### ISSUE TITLE
Python best practices - system exits & logging

### ISSUE THREAD

**Issue by ewels** [ScilifelabDataCentre/dds_cli#78]
## System exits

Doing a hard system exit is an absolute last resort. Normally you want to be raising an exception instead, then probably having a single location right at the top of the code to catch this and do the system exit with non-zero code.

This is especially important if other code packages are importing and using the functions. System exits cannot be caught, so for example if used in the `dds_web` code then these will crash the server. Exceptions can be caught and handled differently depending on where the function is being used.

In most cases here I think it will make sense to create your own exception types. You can then pass the error message in the `raise` statement and log it before exiting downstream (eg. [as done here](https://github.com/nf-core/tools/blob/7721f3742fc30a9e6e46d879404bd1366345092d/nf_core/__main__.py#L251-L253)).

I use this pattern a lot in nf-core and typically do the exit call in the command-line handling code. eg. [here](https://github.com/nf-core/tools/blob/7721f3742fc30a9e6e46d879404bd1366345092d/nf_core/__main__.py#L520-L522). So then if you have 5 subcommands you'll probably have a maximum of 5 exit calls. You can be pretty sure that no-one else will be importing and reusing your cli handling code.

In some cases you have an exit code `0` because it's something like just not having any files to show etc - in other words, normal behaviour. Here you should probably just use `return` to drop out of the function execution early without an exception.

## Logging

You almost never want to print to the console using a `rich` `Console`.

One reason is that this prints to standard out - but most of the current usage is log / status messages. Normally, these should be going to standard error and only the real "results" (eg. the list of projects etc) should go to standard out. This means that command line users can split the output types for downstream use.

Much like the system exits / exceptions, the console calls are not useful for other tools importing the functions. It's better to use the `logging` library instead - then the log messages can be assigned to a namespace and their output customised by any tool using the function (eg. [only showing errors](https://github.com/nf-core/tools/blob/7721f3742fc30a9e6e46d879404bd1366345092d/nf_core/lint/actions_schema_validation.py#L25-L26) or being channeled to a web server log).

Rich [has a logging handler](https://rich.readthedocs.io/en/latest/logging.html) so you can keep the command line outputs looking identical. [Here's how I use it in nf-core](https://github.com/nf-core/tools/blob/7721f3742fc30a9e6e46d879404bd1366345092d/nf_core/__main__.py#L115-L123). My implementation is slightly more complex, as I give the option of _also_ logging to a file, without `rich`. I also enable highlighting / `rich` syntax and have a function that basically makes the colours show up in GitHub Actions CI tests.

**Comment by inaod568** [comment]
Thanks, will go through the code and clean up the stuff I can find!
